# Generated by Django 3.2.6 on 2021-08-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=25)),
                ('social_security_number', models.CharField(max_length=13)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'MAN'), ('W', 'WOMAN')], max_length=1)),
                ('ADDRESS', models.CharField(default='서울', max_length=300)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
