# Generated by Django 3.2.6 on 2021-08-22 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_num',
            new_name='phone_number',
        ),
    ]
