# Generated by Django 3.2.6 on 2021-08-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=2048)),
                ('phone_number', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
    ]
