# Generated by Django 3.2.6 on 2021-08-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=45)),
                ('favorite_food', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
