# Generated by Django 3.2.6 on 2021-08-25 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('postings', '0002_remove_posting_posting_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postingcomment',
            old_name='write_user',
            new_name='comment_user',
        ),
        migrations.AddField(
            model_name='posting',
            name='posting_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
