# Generated by Django 4.0.dev20210810104906 on 2021-08-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=200)),
                ('birth', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
