# Generated by Django 3.2.6 on 2021-08-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('contact_mobile', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
