# Generated by Django 3.2.6 on 2021-08-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=16)),
                ('cell_number', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=50)),
                ('birthday', models.DateField(verbose_name='')),
                ('sex', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
